[package]
name = "noconnect-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr = "0.19.1"
nostr-sdk = "0.19.1"
serde_json = "1.0.93"
thiserror = "1.0.38"
tokio = "1.26.0"
